### ISSUE TITLE
Bugs fixed! Please give me some feedback.

### ISSUE THREAD

**Issue by Dongdongshe** [mikeizbicki/rapache#32]
Hi, Mike. I fix some bugs in rapache. Right now, rapache can handle HTTP GET and POST methods. Also it has daemon mode and supports multiple connections. 
Here is the test cases you can try, first run `./run.sh`
1. case for handling POST method
go to localhost:8080/, there will be a simple html page implementing POST method, where you can send two date, foo and bar. 
2. case for handling GET method
go to localhost:8080/test.sh?foo=bar&bar=foo
3. case for handling file not exists
go to localhost:8080/notexist
4. case for daemon mode 
./run.sh -b

**Comment by mikeizbicki** [comment]
Thanks for the reminder.  You should have feedback now.
